### ISSUE TITLE
queue processing randomly stops

### ISSUE THREAD

**Issue by aelisenko** [beanstalkd/beanstalkd#148]
I have been running beantalkd successfully for many months with no crashes or problems whatsoever. However very recently, I have been getting this issue:

Jobs are added to tubes, beantalkd is running and worker scripts are also running, but for some reason jobs are not being processed. The only fix for this is to restart the workers which are spawned and kills via supervisord.

What could cause a worker that is watching a tube with jobs in it to not process the jobs randomly and create a backlog of jobs?

The workers use the Pheanstalk php library and have worked well for months up to now and there have not been any code changes. There are about 5 tubes doing very different things and they all get hung up together at the same time, the workers are run on several servers with different specs but same OS ubuntu 10.10 so the only common factor between them is Pheanstalk and beantalkd (which is run on one server)

Any insight would be greatly appreciated.

**Comment by chrisbjr** [comment]
Anyone else having this issue? We have been experiencing this with a couple of our apps now (on different servers). We have no idea what errors to be looking for. It just stops processing jobs. Only way to fix for us is to restart. Running on Ubuntu 14.04. Also using the Pheanstalk library.

**Comment by silviucpp** [comment]
What version of beanstalk are you using ? The one from Ubuntu distro ? Because that one is pretty old. 

I created a github project to create a deb for the last master from beanstalkd. I personally don't have any issue with the master. 

https://github.com/silviucpp/beanstalkd-deb

**Comment by silviucpp** [comment]
Also @chrisbjr  what you restarted the server or the workers ? I'm using the erlang client and php one and I didn't found an issue like this( for several months when I integrated bk in my solution) .

**Comment by gjongenelen** [comment]
I know this question doesn't really belong here, but this is the only place I found the same problem. Did one of you found a solution for this annoying problem?

**Comment by silviucpp** [comment]
Hello @gjongenelen ,

I'm using beanstalkd for 3 years in production and processing lot of jobs and never got this issue. You need to describe better your case .. what kind of jobs what libraries are you using... helps if you restart the consumers or problem it's fixed only if server is restarted and so on.

Silviu

**Comment by gjongenelen** [comment]
Okay, but I'm not really sure if this is a problem with beanstalkd. But here we go anyway:

I have 6 workers running on PHP 7.1 (dockerized), with [pda/pheanstalk:3.1.0](https://github.com/pda/pheanstalk)
The payload of the messages is all JSON. 

When I restart the workers, the problem solves itself. But keeps coming back after a few minutes. 
I placed some breakpoints and concluded that the workers hang when they enter the watch-command. The stats-tube command shows an increasing amount of current-jobs-ready.

Full output of stats-tube:
```
current-jobs-urgent: 64
current-jobs-ready: 64
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
total-jobs: 561
current-using: 1
current-watching: 0
current-waiting: 0
cmd-delete: 497
cmd-pause-tube: 0
pause: 0
pause-time-left: 0
```

After a restart of the workers, I don't see any messages of a invalid job being skipped or something. 

I'm thinking about migrating to AWS SQS to quickly solve this problem.

**Comment by silviucpp** [comment]
Problem might be caused by a bug into your driver.. on our side we are using an erlang driver for consuming and  the one you mention for producing. 
Regarding watch command should be done once.. when you open the connection you register what tubes you want to watch .. you don't call this after single message processed...

Silviu

**Comment by chrisbjr** [comment]
Hi guys, after desperately trying to figure out how to fix this issue,
Laravel 5.3 came out with "better handling for queues". Specific to this
was the addition of the timeout parameter.

I didn't know if this issue was related to Laravel but I took the risk and
migrated to Laravel 5.3 (originally from 4.2). After a few hours of
migration, I finally had my queues up and running.

I have 20 queues all processing jobs at the same time and the job involves
database transactions and making API calls. Each queue processes around
1,000 jobs per day.

After experimenting with the timeout parameter of Laravel's queues, I have
finally achieved queues that do not freeze anymore.

My suspicion with this is that the API calls I make probably takes a while
sometimes and times out once in a while. And since Laravel didn't handle
timeouts properly in earlier versions, this caused my queues to freeze
without any indication of what went wrong.

Anyway, this proves that my original issue is not with Beanstalkd but
rather the way earlier versions of Laravel handles queues.

I am now very happy that I don't have to monitor my queues everyday and
they have been running without any restarts or interventions from me for
more than 3 months and running now. Very very happy about this.

**Comment by gjongenelen** [comment]
I have just deployed a hotfix which uses AWS SQS. Tomorrow I will investigate the issues with beanstalkd.
