### ISSUE TITLE
After SIGTERM, jobs in persistent queue file are sometimes corrupt

### ISSUE THREAD

**Issue by wjm2222** [beanstalkd/beanstalkd#157]
We are using beanstalkd 1.5, and rely on the feature that fsync's after every write. Sometimes, when beanstalkd is stopped and restarted, we are finding jobs that have a TTR of 1, which is an unexpected job in our system, and we are detecting that some known jobs have gone missing. Have you seen this behavior? We suspect that the persistent file is getting corrupted by stopping beanstalkd.

The methods we use for stopping beanstalkd are: SIGTERM, SIGKILL, and immediate cold system reset. In those cases where we could do a controlled shutdown, we have not been able to figure out an effective way to do that. The SIGUSR1 drain feature does not help in our application because we need to "put' a job on a status-update queue before we "delete" a job from its task queue. We could benefit from a beanstalkd feature that immediately stops all job/queue processing, guarantees consistency in the persistent file, and exits.

However, this might not resolve the apparent persistent-queue file-corruption problem we have with immediate cold system reset. It seems there are times when that file is vulnerable to losing/corrupting queued-job information if beanstalk is killed.

**Comment by ysmolsky** [comment]
This issue might be fixed in PR #528 and see issue #527 for the details. Before sigterm could happen in the middle of writing and I have no idea what it could lead to. After the fix SIGTERM wont happen in the middle of writing operation for sure. I have not verified this case because I do not have a way to reproduce this. 

Comment from @kr is interesting, but it does not make sense at least to try to handle sigterm if possible.

**Comment by ysmolsky** [comment]
Also see #496 for future work on this.
