### ISSUE TITLE
add the -B flag to clear the binlog

### ISSUE THREAD

**Issue by m1ksoftware** [beanstalkd/beanstalkd#206]
If Beanstalkd is started with the `-b` option (which I'll call session 1), then restarted without `-b` option (session 2) and, again, restarted with `-b` option (session 3), it will reload jobs from session 1. In some cases, this could be ok, in others not.
Maybe could be useful to have a new option (`-B` ?) to clear past existing logs (if they exist). So, using `-B`: 

```
( binlog_exists ) ? clear_binlog_and_start_with_b_option : start_with_b_option
```

What do you think about? I'd need this feature :) and...I could work on it if you think that it might be interesting.

**Comment by JensRantil** [comment]
I think that's a very scary option. Someone being a little sloppy could easily use `-B` instead of `-b`, running beanstalk for a week, restart it and suddenly loose _all_ jobs previously queued. I suggest you instead use a script to start beanstalk, something like this:

```bash
#!/bin/bash
BINLOG=/path/to/binlog
rm -fr $BINLOG/*
beanstalkd -b $BINLOG
```

@m1ksoftware Would this be a reasonable workaround?

**Comment by ysmolsky** [comment]
I would never implement something as this. It's too dangerous to allow. Please use shell commands if you need to clear binlog files.
