### ISSUE TITLE
extend delay/ttr bit-width and specify the types in the protocol

### ISSUE THREAD

**Issue by extemporalgenome** [beanstalkd/beanstalkd#230]
In the protocol doc, bit-widths are unspecified delay, ttr, and job id's. It's important for a client to know how large of an integer will be needed to represent any potential job id the server could send, and if these wraparound. Additionally, it would be useful for maximum durations to be specified, to avoid the beanstalkd returning errors that should be trivially detectable in the client.

**Comment by JensRantil** [comment]
* **delay** is internally stored as nanoseconds in an `int64`. However, it is first temporarily parsed as `uint` in `read_pri`. That means that, according to C specification, it is _at least_ 16bit in size but can be larger depending for which architecture beanstalkd has been compiled for. That is, delay is larger than zero, but has no general upper limit, but can always be smaller than 2^16. For a 64bit architecture, the upper size is [generally 64bit](http://stackoverflow.com/a/7180344).
* **ttr** same as **delay**.
* **jobid** is internally stored a `uint64`. That is, `0 <= jobid < 2^64`.

@kr Could you verify the above? Also, wouldn't it make sense to store `ttr` as and `delay` as uint64 instead to make it easier to document the absolute size in `protocol.txt`? Also, shouldn't they be parsed as uint64, too?

**Comment by JensRantil** [comment]
> Could you verify the above? Also, wouldn't it make sense to store `ttr` as and `delay` as uint64 instead to make it easier to document the absolute size in `protocol.txt`? Also, shouldn't they be parsed as uint64, too?

Also, note that `2^16` seconds is ~18 hours. That's a very short delay time.

**Comment by ysmolsky** [comment]
I think this is important issue with the sizes of data in beanstalkd. We need to streamline this and if possible extend `delay` and `ttr` size to more reasonable uint32 or better uint64.

**Comment by kr** [comment]
Yeah, the documentation here is incomplete and of low quality.

The implementation might be an issue for embedded systems? Most ordinary C compilers today use at least 32 bits for `unsigned int`, so in practice that is probably not an urgent problem. But I agree it should still be fixed.

One option to fix it might be changing the definition of `uint` in dat.h to `unsigned long`. This would actually make its callsite in `read_pri` more correct, since the `strtoul` man page defines it to return `unsigned long`.

(Side note, probably `read_pri` should be renamed `read_num`, and `read_delay` renamed `read_duration`. And then `read_ttr` can be deleted.)
