### ISSUE TITLE
Create a repository for beanstalkd client implemented as a PHP extension

### ISSUE THREAD

**Issue by sergeyklay** [beanstalkd/beanstalkd#391]
/cc @JensRantil

**Comment by JensRantil** [comment]
This issue came out of https://github.com/beanstalkd/beanstalkd/issues/299#issuecomment-413837609.

**Comment by JensRantil** [comment]
@sergeyklay Great with (another) PHP client! I was thinking about this; Instead of putting lots of repositories in the beanstalkd organization, requiring my involvement, also potentially somewhat signaling that it's an official client (which it's not), how about you simply create a public repository with your PHP client on your user and add your client to https://github.com/beanstalkd/beanstalkd/wiki/Client-Libraries?

**Comment by sergeyklay** [comment]
Hmmm, in general sounds good to me. Perhaps we can give this client the status of "official" a little later :)

**Comment by JensRantil** [comment]
:-) Absolutely! Let's do a GitHub star inventory of PHP clients later.
