### ISSUE TITLE
Set up a new webpage outside of the kr.github.io domain

### ISSUE THREAD

**Issue by JensRantil** [beanstalkd/beanstalkd#392]
...to have the community maintain the website.

**Comment by JensRantil** [comment]
New website can be found [here](https://beanstalkd.github.io/). Awaiting reply from Github on removal of [old website](http://kr.github.io/beanstalkd/). Will close this issue when that's done.

I've announced the move [here](https://groups.google.com/d/msg/beanstalk-talk/8ACV4IgH09k/xUwMiTnxAAAJ).

**Comment by gopi-ar** [comment]
Instead of removing the old site, why not redirect it to the new domain? That link comes up first when users search for beanstalkd and [3000+ blogs / repos](https://moz.com/researchtools/ose/links?site=http%3A%2F%2Fkr.github.io%2Fbeanstalkd%2F&filter=&source=external&target=page&group=0&page=1&sort=page_authority&anchor_id=&anchor_type=&anchor_text=&from_site=) link back to this domain.

**Comment by gopi-ar** [comment]
@JensRantil  Looks like the domain's broken without redirection. Again, it's 3000+ links on the internet pointing to the old link.

**Comment by JensRantil** [comment]
@gopi-ar: @kr has been in touch with Github support to see if there's a way to redirect his old website domain to the new website. I'm afraid there's nothing else I can do.

**Comment by JensRantil** [comment]
Github got back and told me the old website was still accessible due to a caching issue. They've cleared the cache now.

**Comment by gopi-ar** [comment]
Can @kr setup an HTML redirect on that page meanwhile? It's a shame if all the resources pointing to beanstalkd say 404.

**Comment by JensRantil** [comment]
I was CC:ed in an email conversation between him and Github. He was looking into it.
