### ISSUE TITLE
sd-daemon.*: replace with libsystemd on Linux

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#501]
I guess this was ripped from some old systemd lib. Does it make sense to link the systemd lib on linux and just use these functions from the lib? while skipping this on other OSes?

If we have to keep it for some reason as it is, how can we test it? And what should we do with functions that are not being used?

I would prefer to get rid of it and just use the lib, but I may be missing something. @kr, can you shed light on the history of this file?

**Comment by kr** [comment]
When I added this file, the [instructions](http://0pointer.de/blog/projects/socket-activation.html) said:

> The `sd_listen_fds()` function call is defined in [sd-daemon.h](http://cgit.freedesktop.org/systemd/plain/src/sd-daemon.h) and [sd-daemon.c](http://cgit.freedesktop.org/systemd/plain/src/sd-daemon.c). These two files are currently drop-in .c sources which projects should simply copy into their source tree.

So that's what I did.

It went on,

> Eventually we plan to turn this into a proper shared library, however using the drop-in files allows you to compile your project in a way that is compatible with socket activation even without any compile time dependencies on systemd.

I never followed systemd development closely, so I didn't know they had got around to making the library. Today I learned! 😆 Now that libsystemd exists, IMO it is totally reasonable to use it.

**Comment by ysmolsky** [comment]
Thank you @justinmayhew !
