### ISSUE TITLE
proposal: setup a process for approving proposals

### ISSUE THREAD

**Issue by ysmolsky** [beanstalkd/beanstalkd#509]
We never discussed this question before and it is briefly mentioned in the Pull Requests section of [CONTRIBUTING.md](https://github.com/beanstalkd/beanstalkd/blob/master/CONTRIBUTING.md):

> If you're making big changes, consider discussing it on the mailing list first. You might save yourself a lot of time if it turns out that the changes you want to make aren't a good fit for the project. This is especially true if you are adding new functionality.

I think the place of the discussion should be changed to this issue tracker. Also proposal of the  feature should contain description of the feature without technical details of implementation. In the case when new command is added, it should contain draft of documentation for this new command. We can review and somewhat formally accept, reject or ask for changes. And cosmetically this can be indicated by labels "Accepted", "Rejected" or no label when discussion of the proposal does not lead to any conclusion. 

Why? 
1. I want to prevent time wasted on implementation of features that will never be added.
3. Every big change to the protocol should be discussed and agreed upon. Adding or modifying command is a very big change.
2. I want to discuss a specification before technical decision is laid out. Design of a feature is an important step; we should not skip it. We should not multiply commands without a real need.

**Comment by kr** [comment]
Great points.

If that document is going to be revised, it might also be nice to suggest that a good way to structure a proposal is in 2 parts: a description of the problem to be solved, focusing just on the problem itself rather than any particular solution, followed by a description of the proposed solution (still omitting technical details that aren’t necessary to evaluate the solution’s suitability to the problem).

Depending on the scope and complexity of the problem, there can be other sections that might help, sich as background information, alternative solutions with reasoning for why they aren’t being proposed, projected maintenance burden, etc. But the 2-part structure described above is a good starting point.

(This doesn’t mean every proposal needs to be elaborate. A simple proposal might just be 2 short sentences. The point is just for the proposal to spend at least a moment focusing on the problem itself first.)

**Comment by ysmolsky** [comment]
Considering how small the traction on this project right now, I doubt this is needed. Closing...
