### ISSUE TITLE
twemproxy (nutcracker) support

### ISSUE THREAD

**Issue by sergeyklay** [beanstalkd/beanstalkd#545]
Hello team,

I would like to start discuss on integration with [twemproxy (nutcracker)](https://github.com/twitter/twemproxy). Initially it was designed as a fast, light-weight proxy for memcached and redis. And I'm interested on beanstalkd support.

**twemproxy features** (copied from project page)

- Fast.
- Lightweight.
- Maintains persistent server connections.
- Keeps connection count on the backend caching servers low.
- Enables pipelining of requests and responses.
- Supports proxying to multiple servers.
- Supports multiple server pools simultaneously.
- Shard data automatically across multiple servers.
- Implements the complete [memcached ascii](https://github.com/twitter/twemproxy/blob/master/notes/memcache.md) and [redis](https://github.com/twitter/twemproxy/blob/master/notes/redis.md) protocol.
- Easy configuration of server pools through a YAML file.
- Supports multiple hashing modes including consistent hashing and distribution.
- Can be configured to disable nodes on failures.
- Observability via stats exposed on the stats monitoring port.
- Works with Linux, *BSD, OS X and SmartOS (Solaris)

Thoughts?

P.S. From discussion with @ysmolsky 
> As for the twemproxy, it looks like it should add support for beanstalkd, and not vice versa. Am I correct?

If we just wait, just because someone should, then we will wait a long time ;-)

First of all, I would like to understand how rational this is. Then - if this is acceptable - what exactly we can to do for such integration and what will the integration look like.

**Comment by ysmolsky** [comment]
I have not investigated that program deeply, but it looks like it solves a problem of distribution data between nodes, I am not sure how it can be applied to beanstalk. beanstalk is different from memcached and redis, as job system vs key-value storage. Can you point out what kind of use case it can solve?

**Comment by sergeyklay** [comment]
In general I'm speaking about [Ambassador pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/ambassador): a way to proxy requests between a pool of beanstalkd nodes (servers).

**Comment by ysmolsky** [comment]
Is this to distribute the load? Technically it can be used, but there will be many edge cases that needs to be explicitly handled. But this solution might end up being too complex. One has to maintain states in both products. I am just speculating, if somebody want to make a proof of a concept, I would be glad to review it.

I just do not see enough motivation to do it myself, since I never been able to move the bottleneck to beanstalkd. I am more concerned with safety guarantees. Also clouds are stealing potential users from beanstalk too. AWS's solution are better marketed and divert big fish companies from using beanstalk. In contrast with SQLite where big fishes are sponsors of it because it can be embed everywhere and there is no alternative in AWS. But I went offtopic here...

**Comment by sergeyklay** [comment]
This is why I would like to discuss this. It is not a real issue, just some thoughts in the direction of cloudification of the beanstalkd I would like to discuss to. Is it right direction? Should we  head this direction? What we can/should do? Can  facilitate the work for those who want to build such a integration? Is there any conceptual restriction to go this direction? etc, etc

**Comment by ysmolsky** [comment]
First of all, there is no easy path to fault-tolerant, distributed message queues. I cannot see how it can be done for beanstalkd without rewriting everything from the ground zero. Adding another tool won't solve the problem. Core reason: data replication, the way it's done, dictates properties of distributed message queue. Look at redis. It is good key-value stored that can be distributed, but it has built-in support for that and was designed that way almost from the start. 

In what direction should beanstalkd evolve? Maybe it's good to leave it as simple as it is with its flaws, but with tuned defaults, fixed critical  bugs and added a couple of features. I wonder why users do not express their wishes anymore. I guess they lost all their hope. This project is dying right now. Only one person doing patches and sculpting the code for the better is not sustainable at all. There have to more people fixing, learning and adding the code to the project, so it won't fade away. There have to be shared burden among many, as their hobby. One can keep up full focus on the project only if being paid for it. I am concerned with this, how do we keep interest of people so that they contribute quality patches too...

And one last worry for us. Maybe this project is done? Like no more critical features that could be add to make it better. I just cannot answer these for two reasons. There is no paying customer who can order features and vote with money. In fact, there is not many not-paying customers anymore as I do not see them actively participating in the issues tracker. So my internal motivation will work only for some more N days and then fade away...

/CC @beanstalkd/maintainers

**Comment by sergeyklay** [comment]
Let's close this one due to the lack of the interest. Feel free open it again if the need arises :)
