### ISSUE TITLE
Multiple consumer worker registered the same ticket

### ISSUE THREAD

**Issue by tfMovamo** [beanstalkd/beanstalkd#579]
I use beanstalkd version 1.10.

Two types of consumer are currently running. php (laravel) and python 3.6.

The python worker (5 pieces) run on one tube and the php worker on another tube (165 pieces).
The workers are started by supervisor.

According to the documentation, a job, if it has been reserved, should not be able to be reserved by any other worker.

However, I cannot confirm this. There seems to be an error here.

I put a job in a tube, for example.
5 python workers are running, this job is now processed randomly between 1 and 5 times. Where once the job.delete () works without problems and then every time an exception is thrown that the ticket does not exist.
This exception was also the beginning of my troubleshooting.
I then created a few logs and only had the jobId output.
All x workers actually registered the same job for themselves.

I got around this by first creating a loc file for each job currently being processed and canceling other workers with the same job.
I hope this bug is still fixed. I am available for any questions.

**Comment by tomponline** [comment]
Can you post your reproducer code here?

**Comment by ptjm** [comment]
What's the ttr on the message?
It's definitely possible for more than one worker to reserve the same job, but it depends on the first worker failing to either delete the job or extend the ttr in time. You'll get the results you're seeing if the ttr is close to the amount of time it normally takes to process the job. One solution is to use a larger ttr, or if there's some reason that's not possible, to have the workers be aware of how much time they have available and either extend it as needed using touch, or stop working and roll back when the time runs out.
I've personally never seen the situation you describe except when the ttr is exceeded, which is by design.
