### ISSUE TITLE
max-job-size of job

### ISSUE THREAD

**Issue by hao159** [beanstalkd/beanstalkd#593]
Hi guy,

I used beanstalk. but current, i have many jobs with 1.000.000 row data . I was set BEANSTALKD_EXTRA to 500mb in config.
But I am not sure if this could have serious performance effects?

what maximum number of bytes can config ?
Thank and best regard!

**Comment by ptjm** [comment]
Maximum value for -z flag is 1GB. There's no performance impact to setting this flag to a large value, but anytime you submit such a large job, it's going to stop the beanstalkd from doing anything else during the time it takes to send and receive those jobs. If you're processing the jobs serially anyway, it won't matter, but if you have a mix of large and small jobs, with multiple consumers, you might want to organize things so that you either have more than one beanstalkd running, with the large jobs going to one and the smaller jobs going to the other, or you have some out-of-beanstalkd channel for delivering the large data.

**Comment by hao159** [comment]
> Maximum value for -z flag is 1GB. There's no performance impact to setting this flag to a large value, but anytime you submit such a large job, it's going to stop the beanstalkd from doing anything else during the time it takes to send and receive those jobs. If you're processing the jobs serially anyway, it won't matter, but if you have a mix of large and small jobs, with multiple consumers, you might want to organize things so that you either have more than one beanstalkd running, with the large jobs going to one and the smaller jobs going to the other, or you have some out-of-beanstalkd channel for delivering the large data.

Thanks for your information!
