### ISSUE TITLE
handle_sigterm_pid1 change exit code from 143 to 0

### ISSUE THREAD

**Issue by GenaANTG** [beanstalkd/beanstalkd#608]
@ysmolsky Hello! Can we change exit code to 0? Docker needs 0 for the correct container stop/shutdown.
Now i have everytime 143 exit code.

https://github.com/beanstalkd/beanstalkd/blob/master/main.c#L39-L43

**Comment by ysmolsky** [comment]
The problem is more general. Beanstalkd is a crash-only software. So it is not supposed to exit gracefully and the only way it can exit is through crash. And crash is not a bad thing - beanstalkd is supposed to handle it without loosing data.

What is the difference between 0 and 143 returned from the process inside container from the point of Docker?
